name: Deploy React based shoe store app using React Router, Material UI and github workflow

on:
  push:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [6.x, 8.x, 10.x, 12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    # Runs a single command using the runners shell
      - name: Install Nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
        
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install #will run yarn install command

      - name: Build
        run: yarn build

      - name: Install Surge
        run: npm install -g surge
      
      - name: Deploy to Surge
        run: surge ./build osama-arif-shoe-store.surge.sh --token ${{ secrets.SURGE_TOKEN }}
